name: Node.js CI

on:
  push:
    branches: [ "deployment-branch" ]
  pull_request:
    branches: [ "deployment-branch" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm install

    - name: Install PM2
      run: npm install pm2 -g

    - name: Restart application with PM2
      run: pm2 start ecosystem.config.js --env production

    - name: Display deployment URL
      run: |
        echo "Your site has been deployed successfully. You can access it at: [URL_DE_VOTRE_SITE]"